// Map of mod note IDs to their descriptions
const MOD_NOTES = {
    1: "Not banned bitch",
  a: "We do not tolerate the doxxing of others.",
  b: "We do not tolerate grooming or child exploitation of any kind.",
  c: "We do not tolerate the sexualization of minors.",
  d: "We do not allow sexual conversations with or solicitation from minors.",
  e: "We do not allow any form of sexual extortion or coercion.",
  f: "We do not allow threats of real-life violence or assault.",
  g: "We do not allow threats to hack or take over accounts.",
  h: "We do not allow credible threats of self-harm or suicide.",
  i: "We do not tolerate attempts to bypass moderation through alts or misdirection.",
  j: "We do not tolerate support, glorification, or promotion of terrorism or violent extremism.",
  k: "We do not allow media containing extremist propaganda or slogans.",
  l: "We do not allow content depicting or celebrating mass shootings.",
  m: "We do not allow fundraising or recruiting for extremist causes.",
  n: "We do not allow content that glorifies, depicts, or describes self-harm or suicide.",
  o: "We do not allow dangerous challenges or stunts that risk user safety.",
  p: "We take threats of suicide seriously and report credible ones to authorities.",
  q: "We do not tolerate harassment, bullying, or targeted abuse.",
  r: "We do not allow impersonation of users, staff, or creators.",
  s: "We do not allow users to ridicule, stalk, or provoke others online or off-platform.",
  t: "We do not tolerate racism, hate speech, or slurs of any kind.",
  u: "We do not allow any form of discriminatory content based on race, gender, religion, disability, or other protected status.",
  v: "We do not tolerate mocking of users based on personal traits or identity.",
  w: "We do not allow NSFW, suggestive, or sexually explicit content.",
  x: "We do not allow sexual jokes or flirtatious behavior between users.",
  y: "We do not allow sexually provocative avatars or assets.",
  z: "We do not allow depictions of gore, death, or physical torture.",
  aa: "We do not allow realistic portrayals of extreme violence or animal cruelty.",
  ab: "We do not allow content designed to shock or disgust viewers.",
  ac: "We do not allow content referencing real-world tragedies or criminal cases.",
  ad: "We do not allow glorification or mockery of victims or disasters.",
  ae: "We do not allow the exploitation of real events for gain or engagement.",
  af: "We do not allow discussion or depiction of drug use, smoking, or alcohol.",
  ag: "We do not allow tutorials or promotion of illegal weapons or criminal behavior.",
  ah: "We do not allow encouragement or normalization of lawbreaking.",
  ai: "We do not allow gambling or simulated gambling games.",
  aj: "We do not allow lotteries or sweepstakes with Robux or real money.",
  ak: "We do not allow casino references in interactive form.",
  al: "We do not allow profanity or bypassing of language filters.",
  am: "We do not allow the use of audio, music, or media that contains swearing.",
  an: "We do not tolerate repeated use of toxic or inflammatory language.",
  ao: "We do not allow political campaigns, slogans, or political references.",
  ap: "We do not allow content involving real political figures or parties.",
  aq: "We do not allow desecration of flags or other national symbols.",
  ar: "We do not allow the use or sharing of exploits or cheat tools.",
  as: "We do not allow scam content, phishing links, or account theft attempts.",
  at: "We do not tolerate impersonation for gain or misleading others.",
  au: "We do not allow spam messages or content flooding.",
  av: "We do not allow misleading metadata or engagement manipulation.",
  aw: "We do not allow redirect content or off-platform baiting.",
  ax: "We do not allow unlicensed use of copyrighted assets or trademarks.",
  ay: "We do not allow stolen code, images, or audio.",
  az: "We do not allow misuse of brand names or trade dress.",
  ba: "We do not allow the sharing or collection of personal data from others.",
  bb: "We do not allow posting of private photos, videos, or identifying info.",
  bc: "We do not allow account trading, token sharing, or login abuse.",
  bd: "We do not allow the posting of unapproved or disguised external links.",
  be: "We do not allow QR codes, shortened URLs, or redirects without authorization.",
  bf: "We do not allow users to drive traffic off-platform without staff approval.",
  bg: "We do not allow users to use other accounts or methods to bypass moderation.",
  bh: "We do not allow users to challenge the mods to Mario Kart for their ban appeals.",
  bi: "We do not allow users under the age of 13 to use our services.",
  bj: "We do not allow users to threaten civil or legal action against the platform or its staff."
};

function getModNoteById(id) {
  return MOD_NOTES[id] || "Unknown moderator note.";
}
